class Form{
    constructor(){
        this.title=createElement('h1');
        this.title.html("Car Racing game");
        this.input=createInput("Name");
        this.button=createButton('Play');
        this.greeting=createElement('h3');
    }
    hide(){
        this.input.hide();
        this.button.hide();
        this.greeting.hide();
    }
    display(){
        this.title.position(displayWidth/2-50,30);
        this.input.position(displayWidth/2-300,150);
        this.button.position(displayWidth/2-30,300);
        this.button.mousePressed(()=>{
            this.input.hide();
            this.button.hide();
            player.name=this.input.value();
            playerCount=playerCount+1;
            player.index=playerCount;
            player.update();
            player.updateCount(playerCount);
            this.greeting.html("Hello"+player.name);
            this.greeting.position(displayWidth/2-40,200);
        })
    }
}